version: "3"
services:
  bot:
    build:
      context: .
    volumes:
      - './main.py:/usr/src/app/main.py'
    environment:
      - ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
      - REFRESH_TOKEN = os.environ["REFRESH_TOKEN"]
      - USER_ID = os.environ["USER_ID"]
      - COOKIE = os.environ["COOKIE"]
      - LATITUDE = os.environ["LATITUDE"]
      - LONGITUDE = os.environ["LONGITUDE"]
      - MATRIX_USERNAME = os.environ["MATRIX_USERNAME"]
      - MATRIX_PASSWORD = os.environ["MATRIX_PASSWORD"]
      - MATRIX_URL = os.environ["MATRIX_URL"]
      - MATRIX_ROOM_ID = os.environ["MATRIX_ROOM_ID"]