version: "3"
services:
  bot:
    build:
      context: .
    volumes:
      - './main.py:/usr/src/app/main.py'
    environment:
      - ACCESS_TOKEN
      - REFRESH_TOKEN
      - USER_ID
      - COOKIE
      - LATITUDE
      - LONGITUDE
      - ROOM_ID
      - LOGIN